### ISSUE TITLE
`sent-time` is not a valid short name for an NGSI-LD attribute

### ISSUE THREAD

**Issue by bobeal** [FIWARE/load-tests#90]
Hi,

The test entity used in the NGSI-LD simulations has an attribute whose short-name is `sent-time`.

However, as per section 4.6.2 of the NGSI-LD specification, this is not an allowed name for an attribute (only Unicode letters and numbers, and `_` are authorized) and a compliant context broker returns a 400 error in such a case.

**Comment by wistefan** [comment]
@bobeal I invited you to the repo, so that you can review https://github.com/FIWARE/load-tests/pull/91 
It should fix the issue. 
Best
Stefan
